import MaleyLean.Papers.BivalenceNonDegenerateReasoning.PaperStatements
import MaleyLean.Papers.BivalenceNonDegenerateReasoning.Surface.Summary

namespace MaleyLean

-- Legacy classical bridge: retained only for compatibility.
#print axioms Papers.BivalenceNonDegenerateReasoning.LegacyDerivedStandingEmergence
#print axioms Papers.BivalenceNonDegenerateReasoning.LegacyPaperStandingConservationDerivedStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.LegacyDerivedStandingSelfEmergence
#print axioms Papers.BivalenceNonDegenerateReasoning.LegacyPaperNoSecondAdmissibilityInvariantDerivedStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.LegacyPaperNoFourthAdmissibilityRoleDerivedStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.LegacyPaperDerivedCoreStatement

-- Current constructive bridge: preferred current route.
#print axioms Papers.BivalenceNonDegenerateReasoning.ConstructiveDerivedStandingEmergence
#print axioms Papers.BivalenceNonDegenerateReasoning.ConstructiveDerivedStandingSelfEmergence
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperStandingConservationConstructiveDerivedStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperNoSecondAdmissibilityInvariantConstructiveDerivedStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperNoFourthAdmissibilityRoleConstructiveDerivedStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperConstructiveDerivedCoreStatement

-- Current axiom-free apex bridge.
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperBivalenceFromApexClosureDerivedStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperNoKernelNeutralGovernanceDifferenceFromApexDerivedStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperLocalClosureOfGovernanceFormFromApexDerivedStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperAASCRealizationFromApexClosureStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperStrictBivalenceFromApexClosureStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperNoSameActRepairStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperGateNecessityStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperFailClosedGovernanceStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperNoSecondAdmissibilityInvariantStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperNoFourthAdmissibilityRoleStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperStandingConservationStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperInferentialLifeExhaustionStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperClosureRelevanceTransmissionStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperGovernanceExhaustionStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperBivalenceOfNonDegenerateReasoningStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperAASCRealizationStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperNoKernelNeutralGovernanceDifferenceStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.PaperLocalClosureOfGovernanceFormStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.Surface.SummaryStatement
#print axioms Papers.BivalenceNonDegenerateReasoning.Surface.ApexSummaryStatement

end MaleyLean
