import MaleyLean.MathClosurePaperStatements

namespace MaleyLean

#print axioms oldTupleDomainPreserved
#print axioms oldGraphRigidity
#print axioms domainFixityOnOldCarrier
#print axioms noCarrierPreservingInternalTotalization
#print axioms PaperAuxiliaryDichotomyStatement
#print axioms noInternalizationByRelabeling
#print axioms supportGovernedFamilyClassified
#print axioms supportGovernedFamilyNoInternalizationByRelabeling
#print axioms mechanismWitnessExists
#print axioms mechanismWitnessSound
#print axioms equivalentInputsShareNormalForm
#print axioms canonicalizationClassified
#print axioms canonicalizationRepresentativeOfEquivalentInputsAgrees
#print axioms canonicalizationNormalFormRespectsEquivalent
#print axioms canonicalizationAsSupportGovernedFamily
#print axioms completionBoundaryClassification
#print axioms completionEmbeddedPointsAreConservative
#print axioms completionReadbackPreservesEmbeddedPoint
#print axioms completionAsSupportGovernedFamily
#print axioms modelImportedWitnessIsExternal
#print axioms modelWitnessClassification
#print axioms modelWitnessAsSupportGovernedFamily
#print axioms forcingClassification
#print axioms forcingGenericWithoutReadbackStaysExternal
#print axioms forcingAsSupportGovernedFamily
#print axioms universalClassification
#print axioms universalInternalComparisonDeterminesStatus
#print axioms universalConstructionAsSupportGovernedFamily
#print axioms interactionClosurePreservesStatus
#print axioms interactionClosureSeedEmbedding
#print axioms flagshipFamiliesUnifiedClassification
#print axioms PaperNoInternalTotalizationStatement
#print axioms PaperExhaustionTheoremStatement
#print axioms PaperDispositionOfFiveMechanismsStatement
#print axioms PaperMechanismWitnessDispositionStatement
#print axioms PaperClosureOfInternalTotalizationStatement
#print axioms PaperNoNewInternalOperatorPowerStatement
#print axioms PaperNoInternalReentryPrincipleStatement
#print axioms PaperConservativeClosureUnderCompositionStatement
#print axioms PaperCompositionIterationNoThirdCaseStatement
#print axioms PaperDiagonalizationPackagingStatement
#print axioms PaperRepresentationChangeStatement
#print axioms PaperNoEmergentFamilyStatement
#print axioms PaperNoInternalReentryByDetourStatement
#print axioms PaperCanonicalizationSelectionQuotientingStatement
#print axioms PaperCompletionEvaluativeClosureStatement
#print axioms PaperModelTheoreticExistenceStatement
#print axioms PaperForcingGenericityAbsolutenessStatement
#print axioms PaperUniversalConstructionStatement
#print axioms PaperFlagshipCaseStudyClosureStatement
#print axioms PaperCompletionReadbackConservativeStatement
#print axioms PaperCompletionReadbackExternalStatement
#print axioms PaperForcingExtensionExternalStatement
#print axioms PaperForcingReadbackConservativeStatement

end MaleyLean
