import MaleyLean.Papers.MeasurementProblemReference.PaperStatements
import MaleyLean.Papers.MeasurementProblemReference.Surface.Summary

namespace MaleyLean

#print axioms Papers.MeasurementProblemReference.PaperCompressedSubstrateNecessityBridgeStatement
#print axioms Papers.MeasurementProblemReference.PaperMeasurementReferenceQuotientTheoremStatement
#print axioms Papers.MeasurementProblemReference.PaperGlobalEquivalenceCollapseTheoremStatement
#print axioms Papers.MeasurementProblemReference.PaperFixationCommutationNecessityForTheoryLevelConfirmationStatement
#print axioms Papers.MeasurementProblemReference.PaperNoAuxiliaryParameterizationOfTheoryLevelConfirmationStatement
#print axioms Papers.MeasurementProblemReference.PaperTheoryLevelConfirmationCriterionStatement
#print axioms Papers.MeasurementProblemReference.PaperReferenceStabilizationNecessityStatement
#print axioms Papers.MeasurementProblemReference.PaperHypothesisOrderReversalInToyModelStatement
#print axioms Papers.MeasurementProblemReference.PaperDiachronicClosureStatement
#print axioms Papers.MeasurementProblemReference.PaperIdentityPreservingLineageTheoremStatement
#print axioms Papers.MeasurementProblemReference.PaperDiachronicInheritanceTheoremStatement
#print axioms Papers.MeasurementProblemReference.PaperDiachronicPracticeDependenceTheoremStatement
#print axioms Papers.MeasurementProblemReference.PaperStructuralLocusTrichotomyStatement
#print axioms Papers.MeasurementProblemReference.PaperSelectorExhaustionTheoremStatement
#print axioms Papers.MeasurementProblemReference.PaperInterpretationTaxonomyStatement
#print axioms Papers.MeasurementProblemReference.PaperUnresolvedAdmissibleDivergenceDestabilizesTheoryLevelScienceStatement

#print axioms Papers.MeasurementProblemReference.PaperMeasurementReferenceQuotientDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperGlobalEquivalenceCollapseDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperFixationCommutationNecessityForTheoryLevelConfirmationDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperEverettianNonSelectionDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperDecoherenceNonSelectionDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperEverettianDownstreamDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperNoAuxiliaryParameterizationOfTheoryLevelConfirmationDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperTheoryLevelConfirmationCriterionDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperReferenceStabilizationCriterionDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperReferenceStabilizationNecessityDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperDiachronicClosureDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperIdentityPreservingLineageDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperDiachronicInheritanceDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperDiachronicPracticeDependenceDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperStructuralLocusTrichotomyDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperSelectorExhaustionDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperInterpretationTaxonomyDerivedStatement
#print axioms Papers.MeasurementProblemReference.PaperMeasurementProblemReferenceDiachronicCurrentStatement
#print axioms Papers.MeasurementProblemReference.PaperMeasurementProblemReferenceSelectorCurrentStatement
#print axioms Papers.MeasurementProblemReference.PaperMeasurementProblemReferenceCurrentDerivedCoreStatement
#print axioms Papers.MeasurementProblemReference.Surface.SummaryStatement
#print axioms Papers.MeasurementProblemReference.Surface.CurrentDerivedSummaryStatement

end MaleyLean
