import MaleyLean.Papers.UnusSolusPossibilisEst.Verbatim.TheoremRegister
import MaleyLean.Papers.UnusSolusPossibilisEst.ManuscriptTheorems
import MaleyLean.Papers.UnusSolusPossibilisEst.Surface.Summary

namespace MaleyLean

#print axioms Papers.UnusSolusPossibilisEst.Verbatim.manuscriptHasApexClosureEntry
#print axioms Papers.UnusSolusPossibilisEst.PaperGateExistenceIsForcedByIrreversibilityAndIntelligibilityStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperBinaryStandingWhenDefinedStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperNoAdmissibilityRelevantParameterizationStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperUniquenessOfAdmissibilityClassificationStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperNoRepairsForAnEvaluatedActStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperNoGeneratorsStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperAnyPrimitiveAuthorizerIsAGatePredicateStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperNoCarriersNumericOrStructuralStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperProbabilityAndTypicalityAreNotPrimitiveStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperExplanationCannotBePrimitiveStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperLegitimacyConservationClosedRegimeStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperNoIllicitScopeTransportStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperTransferWithoutStandingStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperReferenceFixationIsNecessaryForTheoryLevelConfirmationStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperDiscreteMultiplicityEliminationGateFormStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperUniquenessOfTheAdmissibleInteriorStatement
#print axioms Papers.UnusSolusPossibilisEst.PaperApexStandaloneClosureStatement
#print axioms Papers.UnusSolusPossibilisEst.Surface.SummaryStatement

end MaleyLean
