import MaleyLean.YangMillsAssemblyTopNativeSummary
import MaleyLean.YangMillsAssemblyTopNativeCrossHeartLawSummary
import MaleyLean.YangMillsCanonicalVerifiedPayload

namespace MaleyLean

#print axioms YangMillsAssemblyTopNativeSummaryExportStatement
#print axioms YangMillsAssemblyTopNativeCrossHeartLawSummaryExportStatement
#print axioms YangMillsCanonicalVerifiedPayloadTopExportStatement

end MaleyLean
