import MaleyLean.AnomalyYukawaDerivedPaperStatements

namespace MaleyLean

#print axioms PaperAnomalyYukawaEquivalenceStatement
#print axioms PaperNoAnomalyYukawaSplitStatement
#print axioms PaperAnomalyYukawaSharedWitnessStatement
#print axioms PaperNoAnomalyYukawaWitnessSplitStatement

end MaleyLean
