import MaleyLean.LongitudinalGoldstoneDerivedPaperStatements

namespace MaleyLean

#print axioms PaperLongitudinalGoldstoneEquivalenceStatement
#print axioms PaperNoIndependentLongitudinalDegreeStatement
#print axioms PaperLongitudinalGoldstoneSharedWitnessStatement
#print axioms PaperNoLongitudinalGoldstoneWitnessSplitStatement

end MaleyLean
