import MaleyLean.Papers.MeasurementProblemReference.Verbatim.TheoremRegister
import MaleyLean.Papers.MeasurementProblemReference.PaperStatements
import MaleyLean.Papers.MeasurementProblemReference.Surface.Summary
