import MaleyLean.Papers.UnusSolusPossibilisEst.Verbatim.TheoremRegister
import MaleyLean.Papers.UnusSolusPossibilisEst.ManuscriptTheorems
import MaleyLean.Papers.UnusSolusPossibilisEst.DegeneracyCases
import MaleyLean.Papers.UnusSolusPossibilisEst.AxiomMinimality
import MaleyLean.Papers.UnusSolusPossibilisEst.IndependenceModels
import MaleyLean.Papers.UnusSolusPossibilisEst.Surface.Summary
