import MaleyLean.Papers.YangMills.Surface.DependencySkeleton
import MaleyLean.Papers.YangMills.Obligations.Inventory
import MaleyLean.Papers.YangMills.Obligations.PaperLedger
import MaleyLean.Papers.YangMills.Obligations.ClaimLedger
import MaleyLean.Papers.YangMills.Kernel.Register
import MaleyLean.Papers.YangMills.Kernel.PacketRegister
import MaleyLean.Papers.YangMills.Kernel.ReadingOrder
import MaleyLean.Papers.YangMills.Kernel.SeamRegister
import MaleyLean.Papers.YangMills.SourceCrosswalk.Register
import MaleyLean.Papers.YangMills.Verbatim.TheoremRegister
import MaleyLean.Papers.YangMills.Verbatim.DependencySpineSimple
import MaleyLean.Papers.YangMills.Surface.Summary
