import MaleyLean.GodelPaperStatements

namespace MaleyLean

#print axioms PaperInstantiabilityOnFixedDomainStatement
#print axioms PaperSameDomainReadbackStatement
#print axioms PaperGovernanceRelevantCodePredicateReadbackStatement
#print axioms PaperLawfulContentEquivalenceForNegatedCodeStatement
#print axioms PaperSelfSubstitutionClosureStatement
#print axioms PaperNegativeFixedPointSynthesisStatement
#print axioms PaperInferentialNecessityOfClosureDistinctionsStatement
#print axioms PaperFixedDomainInferentialLifeExhaustionStatement
#print axioms PaperClosureRelevanceTransmissionStatement
#print axioms PaperExternalUndecidabilityInertnessStatement
#print axioms PaperTrajectoryNeutralClosureRelevanceActLevelStatement
#print axioms PaperCodePredicateRoleExhaustionStatement
#print axioms PaperNecessaryPackageForSameDomainGodelThreatStatement
#print axioms PaperConcreteDiagonalApparatusStatement
#print axioms PaperNoIndependentGovernanceRelevantCodePredicateStatement
#print axioms PaperGateRenamingCollapseStatement
#print axioms PaperSelfReferencePrerequisiteExhaustionStatement
#print axioms PaperGateCollapsedNegativeFixedPointStatement
#print axioms PaperConcreteGateCollapsedContradictionStatement
#print axioms PaperNoSameDomainDiagonalizationStatement
#print axioms PaperConcreteNoSameDomainDiagonalizationStatement
#print axioms PaperConcreteFailedFixedPointInertnessStatement
#print axioms PaperConcreteFailedBranchNoDiagonalizationStatement
#print axioms PaperTrajectoryLinkedFailedBranchBlockStatement
#print axioms PaperTrajectoryLinkedFailedBranchNoDiagonalizationStatement
#print axioms PaperNoGovernanceRelevantNegativeFixedPointStatement
#print axioms PaperNoSemanticStandingImportStatement
#print axioms PaperNoMetaFoundationalReanchoringStatement
#print axioms PaperInfinitaryAdmissibilityCollapseStatement
#print axioms PaperFiniteSameDomainWitnessStatement
#print axioms PaperExtensionTrichotomyStatement
#print axioms PaperSameDomainExtensionClassificationStatement
#print axioms PaperRescueRouteExhaustionStatement
#print axioms PaperGodelThreatAlignmentStatement
#print axioms PaperTranslationFilterForOrdinaryGodelObjectionsStatement
#print axioms PaperImportedAppendixWitnessLedgerCertifiedStatement
#print axioms PaperImportedAppendixLabelLedgerCertifiedStatement
#print axioms PaperIncompletenessObjectionRouteExhaustionStatement
#print axioms PaperIncompletenessObjectionDataRouteExhaustionStatement
#print axioms PaperNonInstantiabilityOfGodelIncompletenessStatement
#print axioms PaperNonInstantiabilityOfGodelIncompletenessDataStatement
#print axioms PaperGovernanceRelevantClassifierCollapseDerivedStatement
#print axioms PaperInferentialStandingAlignmentDerivedStatement
#print axioms PaperGodelThreatStandingAlignmentDerivedStatement
#print axioms PaperNoGovernanceRelevantTrueButUnprovableSplitDerivedStatement
#print axioms PaperImportedAppendixWitnessBundleDerivedStatement
#print axioms PaperImportedAppendixWitnessLedgerCurrentDerivedStatement
#print axioms PaperRescueRouteExhaustionDerivedStatement
#print axioms PaperConcreteDiagonalApparatusDerivedStatement
#print axioms PaperNoIndependentGovernanceRelevantCodePredicateDerivedStatement
#print axioms PaperSelfReferencePrerequisiteExhaustionDerivedStatement
#print axioms PaperConcreteGateCollapsedContradictionDerivedStatement
#print axioms PaperNoSameDomainDiagonalizationDerivedStatement
#print axioms PaperGodelCodingCurrentDerivedCoreStatement
#print axioms PaperIncompletenessObjectionDataRouteDerivedStatement
#print axioms PaperExplicitScopeThreatBlockedDerivedStatement
#print axioms PaperNonInstantiabilityOfGodelIncompletenessDerivedStatement
#print axioms PaperNonInstantiabilityOfGodelIncompletenessCurrentStatement
#print axioms PaperGodelCurrentDerivedCoreStatement
#print axioms PaperNoGovernanceRelevantTrueButUnprovableSplitStatement
#print axioms PaperStabilityOfUniqueAdmissibleInteriorStatement

end MaleyLean
